export const PRODUCTS_GET = '[SETTINGS] - PRODUCTS/GET';

export const PRODUCT_CREATE = '[SETTINGS] - PRODUCT/CREATE';
export const PRODUCT_REMOVE = '[SETTINGS] - PRODUCT/REMOVE';


export const CATEGORIES_GET = '[SETTINGS] - CATEGORIES/GET';
export const CATEGORY_CREATE = '[SETTINGS] - CATEGORY/CREATE';
export const CATEGORY_REMOVE = '[SETTINGS] - CATEGORY/REMOVE';


export const LABELS_GET = '[SETTINGS] - LABELS/GET';
export const LABEL_CREATE = '[SETTINGS] - LABELS/CREATE';
export const LABEL_REMOVE = '[SETTINGS] - LABELS/REMOVE';