export const SETTINGS_PRODUCTS_SET = '[SETTINGS] - PRODUCTS/SET';
export const SETTINGS_PRODUCTS_PAGE_CHANGE = '[SETTINGS] - PRODUCTS/PAGE_CHANGE';
export const SETTINGS_PRODUCTS_ITEMS_PER_PAGE_CHANGE = '[SETTINGS] - PRODUCTS/ITEMS_PER_PAGE_CHANGE';