version: 2
jobs:
  deploy-to-production:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploying to production
          command: ssh ${user}@${host_production} "mkdir -p ~/veles-dashboard; cd ~/veles-dashboard; git pull; npm i; npm run build;"
workflows:
  version: 2
  deploy-to-vps:
    jobs:
      - deploy-to-production:
          filters:
            branches:
              only: master
