export const IMAGES_GET = '[WEBSITE] - IMAGES/GET';
export const IMAGE_DATA_UPDATE = '[WEBSITE] - IMAGE/UPDATE';
export const IMAGE_REMOVE = '[WEBSITE] - IMAGE/REMOVE';

export const CATEGORIES_GET = '[WEBSITE] - CATEGORIES/GET';
export const CATEGORY_CREATE = '[WEBSITE] - CATEGORY/CREATE';
export const CATEGORY_REMOVE = '[WEBSITE] - CATEGORY/REMOVE';
export const CATEGORY_UPDATE = '[WEBSITE] - CATEGORY/UPDATE';

export const LABELS_GET = '[WEBSITE] - LABELS/GET';
export const LABEL_CREATE = '[WEBSITE] - LABEL/CREATE';
export const LABEL_REMOVE = '[WEBSITE] - LABEL/REMOVE';
export const LABEL_UPDATE = '[WEBSITE] - LABEL/UPDATE';