export const PRODUCTS_GET = '[WEBSITE] - PRODUCTS/GET';
export const PRODUCT_DATA_UPDATE = '[WEBSITE] - PRODUCT/UPDATE';
export const PRODUCT_REMOVE = '[WEBSITE] - PRODUCT/REMOVE';

export const CATEGORIES_GET = '[WEBSITE] - CATEGORIES/GET';
