export const PRODUCTS_GET = '[WEBSITE] - PRODUCTS/GET';
export const PRODUCT_DATA_UPDATE = '[WEBSITE] - PRODUCT/UPDATE';
export const PRODUCT_REMOVE = '[WEBSITE] - PRODUCT/REMOVE';

export const CATEGORIES_GET = '[WEBSITE] - CATEGORIES/GET';
export const CATEGORY_CREATE = '[WEBSITE] - CATEGORY/CREATE';
export const CATEGORY_UPDATE = '[WEBSITE] - CATEGORY/UPDATE';
export const CATEGORY_REMOVE = '[WEBSITE] - CATEGORY/REMOVE';

export const LABELS_GET = '[WEBSITE] - LABELS/GET';
export const LABEL_CREATE = '[WEBSITE] - LABEL/CREATE';
export const LABEL_UPDATE = '[WEBSITE] - LABEL/UPDATE';
export const LABEL_REMOVE = '[WEBSITE] - LABEL/REMOVE';
