export const IMAGES_SET = '[WEBSITE] - IMAGES/SET';
export const PAGE_INDEX_SET = '[WEBSITE] - PRODUCTS/PAGE_INDEX_SET';
export const PAGE_LIMIT_SET = '[WEBSITE] - PRODUCTS/PAGE_LIMIT_SET';

export const CATEGORIES_SET = '[WEBSITE] - CATEGORIES/SET';
export const LABELS_SET = '[WEBSITE] - LABELS/SET';