export const PRODUCTS_SET = '[WEBSITE] - PRODUCTS/SET';
export const PAGE_INDEX_SET = '[WEBSITE] - PRODUCTS/PAGE_INDEX_SET';
export const PAGE_LIMIT_SET = '[WEBSITE] - PRODUCTS/PAGE_LIMIT_SET';

export const CATEGORIES_SET = '[WEBSITE] - CATEGORIES/SET';
