export const IMAGES_SET = '[WEBSITE] - IMAGES/SET';
export const PAGE_INDEX_SET = '[WEBSITE] - PRODUCTS/PAGE_INDEX_SET';
export const PAGE_LIMIT_SET = '[WEBSITE] - PRODUCTS/PAGE_LIMIT_SET';

export const IMAGE_PUBLISH_TOGGLED = '[WEBSITE] - IMAGE/PUBLISH_TOGGLED';
